//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Almanea
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin_Page_Details
    {
        public int Id { get; set; }
        public Nullable<int> Page_Id { get; set; }
        public Nullable<int> FieldType { get; set; }
        public string FieldName { get; set; }
        public Nullable<int> SP { get; set; }
        public Nullable<int> Agent { get; set; }
        public Nullable<int> Supplier { get; set; }
        public Nullable<int> Display { get; set; }
    
        public virtual Admin_Pages Admin_Pages { get; set; }
    }
}
