//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Almanea
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventoy_Details
    {
        public int Id { get; set; }
        public string LabourId { get; set; }
        public string ItemId { get; set; }
        public string ServiceId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> Master_Id { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> UserGroupID { get; set; }
    
        public virtual Inventory_Master Inventory_Master { get; set; }
    }
}
