//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Almanea
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDisplay
    {
        public long Id { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> ProviderId { get; set; }
        public Nullable<int> AjentId { get; set; }
        public bool IsMessasgeSent { get; set; }
        public bool IsOrderReserved { get; set; }
        public Nullable<System.DateTime> Datetime { get; set; }
        public Nullable<int> ReservedBy { get; set; }
    
        public virtual tblOrder tblOrder { get; set; }
    }
}
