//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Almanea
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service_Items
    {
        public int Id { get; set; }
        public Nullable<int> ServiceId { get; set; }
        public Nullable<int> ItemId { get; set; }
        public Nullable<int> quantity { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual tblService tblService { get; set; }
    }
}
