//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Almanea
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAdminUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblAdminUser()
        {
            this.LabourCapacities = new HashSet<LabourCapacity>();
            this.tblOrderAdditionalWorks = new HashSet<tblOrderAdditionalWork>();
            this.tblOrderHistories = new HashSet<tblOrderHistory>();
            this.tblDeliveries = new HashSet<tblDelivery>();
            this.tblComplainHistories = new HashSet<tblComplainHistory>();
            this.tblLaborInactives = new HashSet<tblLaborInactive>();
            this.tblProviderTimeSlots = new HashSet<tblProviderTimeSlot>();
            this.tblLocations = new HashSet<tblLocation>();
        }
    
        public int UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string MobileNo { get; set; }
        public string EncryptedPassword { get; set; }
        public bool Status { get; set; }
        public Nullable<int> UserGroupId { get; set; }
        public Nullable<byte> UserGroupTypeId { get; set; }
        public string IqaamaNo { get; set; }
        public int AccountTypeId { get; set; }
        public string ProfilePic { get; set; }
        public System.DateTime AddedDate { get; set; }
        public int AddedBy { get; set; }
        public string DeviceToken { get; set; }
        public bool LabourIsDriver { get; set; }
        public string DeviceType { get; set; }
        public Nullable<System.DateTime> LastLoggedIn { get; set; }
        public bool IsLogin { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LabourCapacity> LabourCapacities { get; set; }
        public virtual tblUserGroupCompany tblUserGroupCompany { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOrderAdditionalWork> tblOrderAdditionalWorks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOrderHistory> tblOrderHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDelivery> tblDeliveries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblComplainHistory> tblComplainHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLaborInactive> tblLaborInactives { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProviderTimeSlot> tblProviderTimeSlots { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLocation> tblLocations { get; set; }
    }
}
