//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Almanea
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAccountType
    {
        public int AccountTypeId { get; set; }
        public Nullable<int> GroupTypeId { get; set; }
        public string TitleEN { get; set; }
        public string TitleAR { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
