//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Almanea
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAdditionalWork
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblAdditionalWork()
        {
            this.tblOrderAdditionalWorks = new HashSet<tblOrderAdditionalWork>();
            this.tblOrderAdditionalServices = new HashSet<tblOrderAdditionalService>();
        }
    
        public int AdditionalWorkId { get; set; }
        public string AdditionalWorkNameEN { get; set; }
        public string AdditionalWorkNameAR { get; set; }
        public decimal Price { get; set; }
        public Nullable<int> UserGroupId { get; set; }
        public Nullable<short> CategoryrId { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOrderAdditionalWork> tblOrderAdditionalWorks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOrderAdditionalService> tblOrderAdditionalServices { get; set; }
    }
}
