//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Almanea
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblComplainHistory
    {
        public int HistoryId { get; set; }
        public Nullable<int> ComplainId { get; set; }
        public string Comments { get; set; }
        public Nullable<byte> StatusId { get; set; }
        public System.DateTime UpdateOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    
        public virtual tblAdminUser tblAdminUser { get; set; }
    }
}
