//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Almanea
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblComplainType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblComplainType()
        {
            this.tblMultipleComplains = new HashSet<tblMultipleComplain>();
        }
    
        public int ComplainTypeId { get; set; }
        public Nullable<byte> UserGroupTypeId { get; set; }
        public string TitleEN { get; set; }
        public string TitleAR { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public int ComplainCategoryId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblMultipleComplain> tblMultipleComplains { get; set; }
    }
}
