//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Almanea
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDelivery
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblDelivery()
        {
            this.tblDeliveryServices = new HashSet<tblDeliveryService>();
        }
    
        public int DeliveryId { get; set; }
        public int OrderId { get; set; }
        public int DriverId { get; set; }
        public System.DateTime PickupDate { get; set; }
    
        public virtual tblOrder tblOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDeliveryService> tblDeliveryServices { get; set; }
        public virtual tblAdminUser tblAdminUser { get; set; }
    }
}
