//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Almanea
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDeliveryService
    {
        public int DevlieryServiceId { get; set; }
        public int DeliveryId { get; set; }
        public int ServiceId { get; set; }
        public int Quantity { get; set; }
    
        public virtual tblDelivery tblDelivery { get; set; }
        public virtual tblService tblService { get; set; }
    }
}
