//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Almanea
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmail
    {
        public int Id { get; set; }
        public string KeyName { get; set; }
        public string EmailTextEN { get; set; }
        public string EmailTextAR { get; set; }
        public string SubjectEN { get; set; }
        public string SubjectAR { get; set; }
    }
}
