//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Almanea
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLocation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblLocation()
        {
            this.tblOrders = new HashSet<tblOrder>();
        }
    
        public int LocationId { get; set; }
        public string LocationNameEN { get; set; }
        public string LocationNameAR { get; set; }
        public bool Status { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public int UserId { get; set; }
        public Nullable<int> Direction { get; set; }
        public string UserGroupId { get; set; }
    
        public virtual tblAdminUser tblAdminUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOrder> tblOrders { get; set; }
    }
}
