//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Almanea
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMultipleComplain
    {
        public long IIdentity { get; set; }
        public int Complainid { get; set; }
        public int ComplainTypeId { get; set; }
    
        public virtual tblComplainType tblComplainType { get; set; }
        public virtual tblMultipleComplain tblMultipleComplains1 { get; set; }
        public virtual tblMultipleComplain tblMultipleComplain1 { get; set; }
        public virtual tblOrderComplain tblOrderComplain { get; set; }
    }
}
