//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Almanea
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrderAdditionalWork
    {
        public int Id { get; set; }
        public int OrderId { get; set; }
        public int AdditionalWorkId { get; set; }
        public int LabourId { get; set; }
        public int Quantity { get; set; }
        public int Price { get; set; }
        public int Total { get; set; }
    
        public virtual tblAdditionalWork tblAdditionalWork { get; set; }
        public virtual tblOrder tblOrder { get; set; }
        public virtual tblAdminUser tblAdminUser { get; set; }
    }
}
