//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Almanea
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrderAdditionalService
    {
        public int AdditionalServiceId { get; set; }
        public int OrderId { get; set; }
        public int UserId { get; set; }
        public int Quantity { get; set; }
        public decimal Price { get; set; }
        public decimal SpareParts { get; set; }
        public System.DateTime AddedOn { get; set; }
        public bool Status { get; set; }
        public int AdditionalWorkId { get; set; }
    
        public virtual tblAdditionalWork tblAdditionalWork { get; set; }
        public virtual tblOrder tblOrder { get; set; }
    }
}
