//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Almanea
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrderComplain
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblOrderComplain()
        {
            this.tblMultipleComplains = new HashSet<tblMultipleComplain>();
        }
    
        public int ComplainId { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> ComplainTypeId { get; set; }
        public string Subject { get; set; }
        public string Comments { get; set; }
        public byte StatusId { get; set; }
        public System.DateTime AddedOn { get; set; }
        public string Response { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public Nullable<byte> ComplainBy { get; set; }
        public Nullable<int> AddedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblMultipleComplain> tblMultipleComplains { get; set; }
        public virtual tblOrder tblOrder { get; set; }
    }
}
