//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Almanea
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblOrder()
        {
            this.OrderDisplays = new HashSet<OrderDisplay>();
            this.tblDeliveries = new HashSet<tblDelivery>();
            this.tblOrderAdditionalServices = new HashSet<tblOrderAdditionalService>();
            this.tblOrderAdditionalWorks = new HashSet<tblOrderAdditionalWork>();
            this.tblOrderComplains = new HashSet<tblOrderComplain>();
            this.tblOrderHistories = new HashSet<tblOrderHistory>();
            this.tblOrderReleases = new HashSet<tblOrderReleas>();
            this.tblOrderServices = new HashSet<tblOrderService>();
            this.tblTeamCapacityCalculations = new HashSet<tblTeamCapacityCalculation>();
            this.OrdersAssigneds = new HashSet<OrdersAssigned>();
        }
    
        public int OrderId { get; set; }
        public string SellerName { get; set; }
        public string SellerContact { get; set; }
        public string InvoiceNo { get; set; }
        public string CustomerName { get; set; }
        public string CustomerContact { get; set; }
        public string AlternateMobile { get; set; }
        public int LocationId { get; set; }
        public Nullable<System.DateTime> InstallDate { get; set; }
        public byte PrefferTime { get; set; }
        public byte Status { get; set; }
        public System.DateTime AddedDate { get; set; }
        public int SupplierId { get; set; }
        public int AddedBy { get; set; }
        public int ReservedProvider { get; set; }
        public Nullable<int> ReservedBy { get; set; }
        public byte PreferDate { get; set; }
        public Nullable<int> PrefferHr { get; set; }
        public Nullable<byte> PrefferMeridian { get; set; }
        public string CustomerCode { get; set; }
        public bool IsOnEdit { get; set; }
        public string CustomerSignOff { get; set; }
        public Nullable<bool> SmsInArabic { get; set; }
        public Nullable<decimal> ServiceTotal { get; set; }
        public Nullable<decimal> ServiceVat { get; set; }
        public Nullable<decimal> AdditionalTotal { get; set; }
        public Nullable<decimal> AdditionalVat { get; set; }
        public decimal TotalAmount { get; set; }
        public Nullable<bool> ReportAdmin { get; set; }
        public string Comments { get; set; }
        public string AssignedTo { get; set; }
        public int LabourId { get; set; }
        public Nullable<int> DriverId { get; set; }
        public string InvoiceImages { get; set; }
        public string DeliveryStatus { get; set; }
        public string CustomerLngLat { get; set; }
        public string WhyPartial { get; set; }
        public Nullable<int> AdditionalWorkOtp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDisplay> OrderDisplays { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDelivery> tblDeliveries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOrderAdditionalService> tblOrderAdditionalServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOrderAdditionalWork> tblOrderAdditionalWorks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOrderComplain> tblOrderComplains { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOrderHistory> tblOrderHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOrderReleas> tblOrderReleases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOrderService> tblOrderServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTeamCapacityCalculation> tblTeamCapacityCalculations { get; set; }
        public virtual tblLocation tblLocation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdersAssigned> OrdersAssigneds { get; set; }
    }
}
