//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Almanea
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrderService
    {
        public int OrderServiceId { get; set; }
        public int OrderId { get; set; }
        public int ServiceId { get; set; }
        public int Quantity { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> IsAdditional { get; set; }
        public int Unit { get; set; }
    
        public virtual tblOrder tblOrder { get; set; }
        public virtual tblService tblService { get; set; }
    }
}
