//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Almanea
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProviderTimeSlot
    {
        public int Id { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<System.DateTime> InstallDate { get; set; }
        public Nullable<int> ServiceProviderId { get; set; }
        public Nullable<int> Prefer { get; set; }
        public Nullable<int> BookSlot { get; set; }
        public Nullable<int> LabourId { get; set; }
        public Nullable<System.DateTime> Updatedate { get; set; }
        public Nullable<int> StartHour { get; set; }
        public Nullable<int> EndHour { get; set; }
        public Nullable<int> TotalConsumedHour { get; set; }
    
        public virtual tblUserGroupCompany tblUserGroupCompany { get; set; }
        public virtual tblAdminUser tblAdminUser { get; set; }
    }
}
