//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Almanea
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProviderSettingMapper
    {
        public int Id { get; set; }
        public Nullable<int> ServiceProviderId { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public Nullable<bool> IsInternal { get; set; }
    }
}
