//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Almanea
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPushNotification
    {
        public int Id { get; set; }
        public string KeyName { get; set; }
        public string PushNotificationTextEN { get; set; }
        public string PushNotificationTextAR { get; set; }
    }
}
