//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Almanea
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblResetOrder
    {
        public int Id { get; set; }
        public int OrderId { get; set; }
        public Nullable<System.DateTime> InstallDate { get; set; }
        public Nullable<byte> PrefferTime { get; set; }
        public Nullable<byte> PreferDate { get; set; }
        public Nullable<int> PrefferHr { get; set; }
        public Nullable<byte> PrefferMeridian { get; set; }
    }
}
