//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Almanea
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblServiceMapper
    {
        public long Id { get; set; }
        public Nullable<int> ServiceId { get; set; }
        public Nullable<int> ServiceProviderId { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public string Estimated { get; set; }
        public Nullable<int> WorkingHours { get; set; }
        public bool IsWorking { get; set; }
        public bool ServiceAcceptStatus { get; set; }
    
        public virtual tblService tblService { get; set; }
    }
}
