//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Almanea
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblService
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblService()
        {
            this.tblDeliveryServices = new HashSet<tblDeliveryService>();
            this.tblOrderServices = new HashSet<tblOrderService>();
            this.tblServiceMappers = new HashSet<tblServiceMapper>();
            this.OrdersAssigneds = new HashSet<OrdersAssigned>();
            this.Service_Items = new HashSet<Service_Items>();
        }
    
        public int ServiceId { get; set; }
        public string ServiceNameEN { get; set; }
        public string ServiceNameAR { get; set; }
        public decimal UnitPrice { get; set; }
        public bool Status { get; set; }
        public System.DateTime AddedDate { get; set; }
        public int UserId { get; set; }
        public string ServiceProviderId { get; set; }
        public string SupplierId { get; set; }
        public bool IsDisplay { get; set; }
        public Nullable<short> CategoryId { get; set; }
        public string Estimatetime { get; set; }
        public Nullable<int> ServId { get; set; }
        public Nullable<int> InventoryRequired { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDeliveryService> tblDeliveryServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOrderService> tblOrderServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblServiceMapper> tblServiceMappers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdersAssigned> OrdersAssigneds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Service_Items> Service_Items { get; set; }
    }
}
